/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline: string;
            paragraph?: string | null;
            services?:
              | {
                  title: string;
                  icon?: string | null;
                  description?: string | null;
                  image_url?: (string | null) | Media;
                  duration?: string | null;
                  cta_text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'detailed_services';
          }
        | {
            heading: string;
            subheading?: string | null;
            label?: string | null;
            url?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading: string;
            content?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'story';
          }
        | {
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'credibility';
          }
        | {
            badge?: string | null;
            heading: string;
            highlightedText?: string | null;
            subheading?: string | null;
            services?:
              | {
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            viewAllCta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceshighlight';
          }
        | {
            badge?: string | null;
            heading: string;
            subheading?: string | null;
            image_url?: string | null;
            floatingStat?: {
              value?: string | null;
              label?: string | null;
            };
            features?:
              | {
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'whychooseus';
          }
        | {
            anchor?: string | null;
            eyebrow?: string | null;
            heading?: string | null;
            highlightedText?: string | null;
            headingSuffix?: string | null;
            subheading?: string | null;
            dentists?:
              | {
                  name: string;
                  role?: string | null;
                  qualification?: string | null;
                  experience?: string | null;
                  image_url: string;
                  id?: string | null;
                }[]
              | null;
            viewAllCta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'dentistsgrid';
          }
        | {
            anchor?: string | null;
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            before_image_url: string;
            after_image_url: string;
            before_label?: string | null;
            after_label?: string | null;
            viewAllCta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'smilegallery';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            stats?:
              | {
                  icon?: string | null;
                  value?: string | null;
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            badges?:
              | {
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trustsection';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            reviews?:
              | {
                  quote: string;
                  author_name: string;
                  author_role?: string | null;
                  avatar_url?: string | null;
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            trust_badge?: {
              icon_url?: string | null;
              text?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialcarousel';
          }
        | {
            anchor?: string | null;
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            map_url: string;
            contact_details?:
              | {
                  icon?: string | null;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            primary_cta?: {
              label?: string | null;
              url?: string | null;
            };
            secondary_cta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactsection';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        detailed_services?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              paragraph?: T;
              services?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    description?: T;
                    image_url?: T;
                    duration?: T;
                    cta_text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              label?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        credibility?:
          | T
          | {
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceshighlight?:
          | T
          | {
              badge?: T;
              heading?: T;
              highlightedText?: T;
              subheading?: T;
              services?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    url?: T;
                    id?: T;
                  };
              viewAllCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whychooseus?:
          | T
          | {
              badge?: T;
              heading?: T;
              subheading?: T;
              image_url?: T;
              floatingStat?:
                | T
                | {
                    value?: T;
                    label?: T;
                  };
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dentistsgrid?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              highlightedText?: T;
              headingSuffix?: T;
              subheading?: T;
              dentists?:
                | T
                | {
                    name?: T;
                    role?: T;
                    qualification?: T;
                    experience?: T;
                    image_url?: T;
                    id?: T;
                  };
              viewAllCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        smilegallery?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              before_image_url?: T;
              after_image_url?: T;
              before_label?: T;
              after_label?: T;
              viewAllCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        trustsection?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              stats?:
                | T
                | {
                    icon?: T;
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              badges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialcarousel?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              reviews?:
                | T
                | {
                    quote?: T;
                    author_name?: T;
                    author_role?: T;
                    avatar_url?: T;
                    rating?: T;
                    id?: T;
                  };
              trust_badge?:
                | T
                | {
                    icon_url?: T;
                    text?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactsection?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              map_url?: T;
              contact_details?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              primary_cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondary_cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo_text?: string | null;
  logo_url?: string | null;
  nav_links?:
    | {
        label: string;
        link: string;
        mega_items?:
          | {
              label: string;
              link: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  secondary_cta_text?: string | null;
  secondary_cta_link?: string | null;
  cta_text?: string | null;
  cta_link?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  trust_badges?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  image_url?: string | null;
  logo_text?: string | null;
  description?: string | null;
  socials?:
    | {
        icon?: string | null;
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  columns?:
    | {
        title?: string | null;
        items?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    title?: string | null;
    description?: string | null;
    placeholder?: string | null;
    button_text?: string | null;
  };
  copyright_text?: string | null;
  legal_links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo_text?: T;
  logo_url?: T;
  nav_links?:
    | T
    | {
        label?: T;
        link?: T;
        mega_items?:
          | T
          | {
              label?: T;
              link?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  secondary_cta_text?: T;
  secondary_cta_link?: T;
  cta_text?: T;
  cta_link?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  trust_badges?:
    | T
    | {
        label?: T;
        id?: T;
      };
  image_url?: T;
  logo_text?: T;
  description?: T;
  socials?:
    | T
    | {
        icon?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
        placeholder?: T;
        button_text?: T;
      };
  copyright_text?: T;
  legal_links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}